03_Django_curd/articles/urls.py
from django.urls import path
from . import views


app_name = 'articles'
# /articles/ ___
urlpatterns = [
    path('', views.index, name='index'),  # 비워두면 articles/와 같은 것
    # path('new/', views.new, name='new'),  # articles에 있는 new
    path('create/', views.create, name='create'),

    # /articles/3/
    path('<int:article_pk>/', views.detail, name='detail'),
        # detail 우리는 이름만 보고 갈 것이므로 <int:article_pk>/ 가 <int:article_pk>/detail/ 로 바뀌어도 괜찮
    
    # /articles/4/delete/ -> 삭제를 하겠다
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    path('<int:article_pk>/update/', views.update, name='update'),

    # /articles/3/comment
    path('<int:article_pk>/comments/', views.comments_create, name='comments_create'),

    # /articles/3/comments/2/delete  
    # url이 길어지면, name이 꼭 필요하게 됨
    path('<int:article_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
]


# 2) 자원에 대한 행위는 HTTP Method(GET, POST, PUT, DELETE 등)로 표현
# get : 정보를 주세요라는 요청(가지고오다)
# post : 작성하라(등록해주세요)
# delete : 삭제
# put : 정보 수정
# html에서는 POST나 GET

03_Django_curd/crud/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # jobs로 들어왔다면 jobs/url.py로 이동해라
    path('jobs/', include('jobs.urls')),
    # articles로 들어왔다면 articles/url.py로 이동해라
    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),
]

# 사용자가 Media파일이 있는 곳으로 올 수 있는 경로 추가
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

03_Django_curd/jobs/urls.py
from django.urls import path
from . import views

app_name = 'jobs'
# /jobs/ ___
urlpatterns = [
    path('', views.name, name='name'),
    path('past_job/', views.past_job, name='past_job'),
]

03_Django_curd/articles/models.py
from django.db import models
from imagekit.processors import Thumbnail
from imagekit.models import ImageSpecField

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=20)  # 어떤 field정의할지
    # 문자열은 null=True 넣지 말기 blank만 넣기(=빈문자열 넣기 위해), 다른 field는 blank, null 다 사용 가능
    content = models.TextField(blank=True)  # String 문자열 빈 값 저장은 null이 아니라 '' -> null이 적합하지 않음
    # blank: 데이터 유효성과 관련되어 있다. -> 비어있어도 저장해도 괜찮아.(필수는 아니야~)
    # null: 실제 DB와 관련되어 있다. -> 값이 비어있어도 Null로 두지말고 비어두어라
    # '', Null로 저장할 것인지
    image = models.ImageField(blank=True)
    image_thumbnail = ImageSpecField(
        source='image',
        processors=[Thumbnail(200,200)],
        format='JPEG',
        options={'quality': 90},
    )
    created_at = models.DateTimeField(auto_now_add=True)  # auto_now와 비교!
    updated_at = models.DateTimeField(auto_now=True)


class Comment(models.Model):
    # on_delete=models.CASCADE == 'Article 이 삭제되면 Comment도 함께 삭제'
    # 어떤 게시글에 대한 댓글인지 알려주기위해서!
    # article.comment_set이 자동으로 생성-> 이름을 article.comments로 바꿔주기 위해서
    # related_name == 'Article instance가 comment를 역참조 할 수 있는 이름을 정의'
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comments')  # 이 article을 참조하겠다
    # 1:N 관계에서 바라보고있던 article(게시글)이 삭제되었다면 그 관련 데이터(댓글)도 삭제해라\
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-pk']
        # ex. 사진 데이터는 내용이고, meta data는 파일이름, 찍은 날짜, 크기 등등

    def __str__(self):
        return self.content

03_Django_curd/jobs/models.py
from django.db import models

# Create your models here.
class Job(models.Model):
    name = models.CharField(max_length=20)
    past_job = models.TextField()
    profile_image = models.ImageField(blank=True)

    def __str__(self):  # 데이터가 어떻게 생성되는지 보여줌
        return self.name  # ex. <Job (3)>를 <Job 김선재>로 보여줌

03_Django_curd/articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Article, Comment


# articles의 메인 페이지, article list를 보여줌
def index(request):
    # SELECT * FROM articles
    articles = Article.objects.all()
    context = {'articles': articles}
    return render(request, 'articles/index.html', context)



# Variable Routing으로 사용자가 보기를 원하는 페이지 pk를 받아서
# Detail 페이지를 보여준다.
def detail(request, article_pk):
    # SELECT * FROM articles WHERE pk=3
    article = get_object_or_404(Article, pk=article_pk)
    comments = article.comments.all()  # 모든 정보 가지고와라
    context = {
        'article': article,
        'comments': comments
        }
    return render(request, 'articles/detail.html', context)



# 입력 페이지 제공
# GET /articles/create/ -> 페이지만 받아 가겠다
# def new(request):
#     return render(request, 'articles/new.html')  # 자기 페이지갈때 쓰는 것이 render



# 데이터를 전달받아서 article 생성
# POST /articles/create -> new와 create를  GET, POST를 통해 돌아가게함
def create(request):

    # 만약 GET요청으로 들어오면 html 페이지 rendering
    if request.method == 'POST':
        # /articles/new의 new.html의 form에서 전달받은 데이터들
        title = request.POST.get('title')  # POST하면 들어올정보
        content = request.POST.get('content')
        image = request.FILES.get('image')
        article = Article(title=title, content=content, image=image)  # 새로운 인스턴스 생성
        article.save()
        
        return redirect('articles:detail', article.pk)  # 다른 페이지에 갈때 쓰는 것이 redirect
        # 이쪽으로 바로 이동해라. -> 이때, index함수로 가게 됨

    # 아니라면(POST일 경우) 사용자 데이터 받아서 article 생성
    else:
        return render(request, 'articles/create.html')
 
       
    

# 사용자로부터 받은 article_pk값에 해당하는 article을 삭제한다.
def delete(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    if request.method == 'POST':
        article.delete()
        return redirect('articles:index')
    else:
        return redirect('articles:detail', article_pk)
 # articles에 url에서 index로 만들었는데, 만약 articles말고 movies 앱이 생겼을 때, 각각 url이 생길텐데, 
 # 다 index로 하면 어느 앱에 있는 index 페이지인지 헷깔림.
 # 그래서 templates에 name space를 지정해준 것처럼 하면 ok


# /articles/5/update/
def update(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    # POST /article/update : 실제 Update 로직이 수행
    if request.method == 'POST':
        title = request.POST.get('title')
        content = request.POST.get('content')
        image = request.FILES.get('image')
        if image:
            article.image = image
        article.title = title
        article.content = content
        article.save()
        return redirect('articles:detail', article.pk)

    # GET /article/update : Update를 하기 위한 Form을 제공하는 페이지
    else:
        article = get_object_or_404(Article, pk=article_pk)
        context = {'article': article}
        return render(request, 'articles/update.html', context)

    
def comments_create(request, article_pk):
    # article_pk에 해당하는 article에 새로운 comment 생성
    article = Article.objects.get(pk=article_pk)
    if request.method == 'POST':
        content = request.POST.get('content')
        comment = Comment()

        # 객체를 통째로 넘겨줌. 어떤 article에 대한 comment인지 알려주기 위한 작업
        comment.article = article
        # comment.article_id = article_pk 라고 해도 ok
        # 이 둘의 차이점은 없음!

        comment.content = content
        comment.save()
        
        # 생성한 다음 detail page로 redirect
    return redirect('articles:detail', article.pk)


def comments_delete(request, article_pk, comment_pk):
    # POST요청으로 들어왔다면
    if request.method == 'POST':
    # comment_pk에 해당하는 댓글 삭제
        comment = get_object_or_404(Comment, pk=comment_pk)  # 특정 모델가지고오고 없으면, 404페이지 보여줌
        comment.delete()
    # 댓글 삭제 후, detail 페이지로 돌아감
    return redirect('article:detail', article_pk)

03_Django_curd/jobs/views.py
from django.shortcuts import render
from .models import Job
from faker import Faker

# Create your views here.
def name(request):
    return render(request, 'jobs/name.html')


def past_job(request):
    fake = Faker('ko_kr')
    name = request.POST.get('name')
    profile_image = request.FILES.get('profile_image')
    if not Job.objects.filter(name=name):  
        job = Job()
        job.name = name
        job.profile_image = profile_image
        job.past_job = fake.job()
        job.save()
    job = Job.objects.get(name=name)
    
    context = {'job': job}
    return render(request, 'jobs/past_job.html', context)

03_Django_curd/articles/templates/articles/create.html
{% extends 'base.html' %}

{% block title %}New Article{% endblock title %}

{% block body %}
  <h1>New Article</h1>
  <form action="{% url 'articles:create' %}" method="POST" enctype="multipart/form-data">  {% comment %} /를 붙여야 동일한 앱 내에서 이동 {% endcomment %}
    {% csrf_token %} {% comment %}  이 쿠키는 보안상의 이유로 필요 {% endcomment %}
    <input type="text" name="title"><br>
    <textarea name="content" cols="30" rows="10"></textarea><br>
    <label for="image">이미지: </label>
    <input type="file" name="image" id="image" accept="image/*"><br>
    <button type="submit">생성하기</button>
  </form>
{% endblock body %}

03_Django_curd/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block title %}Article Detail{% endblock title %}

{% block body %}
  <h1>{{ article.title }}</h1>
  <p>작성일자: {{ article.created_at }}</p>
  <hr>
  {% if article.image %}
    <img src="{{ article.image.url }}" alt="{{ article.image }}">
  {% endif %}
  <p>{{ article.content }}</p>
  <hr>
  <h4>Comments</h4>
  {% comment %} 댓글 작성을 위한 form {% endcomment %}
  <form action="{% url 'articles:comments_create' article.pk %}" method="POST">
  {% csrf_token %}
    <input type="text" name="content">
    <button type="submit">댓글 작성</button>
  </form>

  <ul>
  {% for comment in comments %}
    <li>
      {{ comment.content }}
      <form action="{% url 'articles:comments_delete' article.pk comment.pk %}" method="POST">
        {% csrf_token %}
        <button type="submit">[삭제하기]</button>
      </form>
    </li>
  {% empty %}
    <p>아직 댓글이 없습니다.. </p>
  {% endfor %}
  </ul>
  <hr>

  <a href="{% url 'articles:index' %}">[뒤로가기]</a>
  <a href="{% url 'articles:update' article.pk %}">[수정하기]</a>
  <form action="{% url 'articles:delete' article.pk %}" method="POST" onclick="return confirm('Are you sure?')">
  {% csrf_token %}
  <button type="submit">삭제하기</button>
  </form>
{% endblock body %}

03_Django_curd/articles/templates/articles/index.html
{% extends 'base.html' %}  {% comment %} extends는 최상단, load static은 그 밑에 {% endcomment %}
{% load static %}  {% comment %} static 파일들을 불러오겠다. {% endcomment %}

{% block title %}Articles{% endblock title %}

{% block body %}
  <h1>Articles</h1>
  <a href="{% url 'articles:create' %}">[작성하기]</a>  {% comment %} 이동시키겠다 {% endcomment %}
  <img src="{% static 'articles/images/풍경.jpg' %}" alt="">
  <hr>
  {% comment %} article list들 보여줌 {% endcomment %}
  {% for article in articles %}
  <div>
    {% comment %} 1. 안녕하세요 {% endcomment %}
    {% if article.image %}
      <img src="{{ article.image_thumbnail.url }}" alt="{{ article.image_thumbnail }}">
    {% endif %}
    <h3><a href="{% url 'articles:detail' article.pk %}">{{ article.pk }}. {{ article.title }}</a></h3>
    <p>{{ article.content }}</p>
  </div>
  <br>
  {% endfor %}
{% endblock body %}

03_Django_curd/articles/templates/articles/new.html
{% extends 'base.html' %}

{% block title %}New Article{% endblock title %}

{% block body %}
  <h1>New Article</h1>
  <form action="{% url 'articles:create' %}">  {% comment %} /를 붙여야 동일한 앱 내에서 이동 {% endcomment %}
    <input type="text" name="title"><br>
    <textarea name="content" cols="30" rows="10"></textarea><br>
    <button type="submit">생성하기</button>
  </form>
{% endblock body %}

03_Django_curd/articles/templates/articles/update.html
{% extends 'base.html' %}
​
{% block title %}Update{% endblock title %}
​
{% block body %}
  <h1>Update Article</h1>
  {% if article.image%}
  <img src="{{ article.image.url }}" alt="{{ article.image }}">
  <form action="{% url 'articles:update' article.pk %}" method="POST" enctype="multipart/form-data">   {% comment %} /를 붙여야 동일한 앱 내에서 이동 {% endcomment %}
      {% csrf_token %}  {% comment %}  이 쿠키는 보안상의 이유로 필요 {% endcomment %}
      <input type="text", name="title" value={{ article.title }}><br/>
      <textarea name="content" cols="30" rows="10">{{ article.content }}</textarea><br/>
      <label for="image">이미지: </label>
      <input type="file" name="image" id="image"><br>
      <button type="submit">수정하기</button>
  </form>
  <a href="{% url 'articles:detail' article.pk %}">[뒤로 가기]</a>
​
​
{% endblock body %}

03_Django_curd/crud/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'base.css' %}">
  <link rel="shortcut icon" href="{% static 'favicon-96x96.png' %}" type="image/x-icon">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{% block title %}{% endblock title %}</title>
</head>
<body>
  {% block body %}
  {% endblock body %}
</body>
</html>

03_Django_curd/jobs/templates/jobs/name.html
{% extends 'base.html' %}

{% block title %}Name{% endblock title %}

{% block body %}
  <h3>이름을 입력해주세요~!</h3>
  {% comment %} 이 부분은 사진을 저장하겠다는 것! {% endcomment %}
  {% if jobs.profile_image %}
    <img src="{{ jobs.profile_image.url }}" alt="{{ jobs.profile_image }}">
  {% endif %}

  <form action="{% url 'jobs:past_job' %}" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <input type="text" name="name"><br><br>
  <input type="file" name="profile_image" id="profile_image" accept="image/*"><br><br>
  <button type="submit">[작성하기]</button>
  </form>
{% endblock body %}

03_Django_curd/jobs/templates/jobs/past_job.html
{% extends 'base.html' %}

{% block title %}Past_job{% endblock title %}

{% block body %}
  <h2>당신의 전생 직업은?</h2>
  {% if job.profile_image %}
    <img src="{{ job.profile_image.url }}" alt="{{ job.profile_image }}">
  {% endif %}
  <p>{{ job.name }}님의 전생의 직업은 <span style="color: blue;">{{ job.past_job }}</span>입니다</p>
  <a href="{% url 'jobs:name' %}">[다시하기]</a>
{% endblock body %}