06_Django_study/review2/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

# urlpatterns가 있어야 error가 안남 -> list 우선적으로 만들자!
urlpatterns = [
    # 회원가입 url 
    path('signup/', views.signup, name='signup'),
    # 로그인 url
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    # 회원탈퇴
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
        # 로그인이 되어있기때문에, user의 정보를 id값으로 판별할 필요가 없음 -> pk값 필요없음
    path('password/', views.password, name='password'),
]

06_Django_study/review2/articles/urls.py
# review에서 articles로 보내라했기 때문에 articles에서도 urls.py가 있어야 에러가 안남. 
from django.urls import path
from . import views  # 현재 app에서 view를 가지고오겠다 -> .=현재 앱

app_name = 'articles'

urlpatterns = [
    # index:현재 있는 모든 아티클들을 보여줌
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),  # 여러 앱에서 create라는 함수가 있을 수 있는데, 이름을 지정하면 이름이 나올 때 가라!
    path('<int:article_pk>/', views.detail, name='detail'),
    path('<int:article_pk>/update/', views.update, name='update'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    path('<int:article_pk>/like/', views.like, name='like'),
    path('<int:article_pk>/comment/', views.comment_create, name='comment_create'),
    path('<int:article_pk>/comment/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
    # 선생님 코드
    # path('<int:article_pk>/comments/', views.comment_create, name='comment_create'),  article_pk번째 article에 comments를 생성하겠다.
    # 삭제 시에는 article_pk가 필요없을 수도 있지만, 상속성을 나타내기 위해서
    # path('<int:article_pk>/comment/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
    path('<int:article_pk>/follow/<int:user_pk>/', views.follow, name='follow')
]

06_Django_study/review2/review/urls.py
from django.contrib import admin
from django.urls import path, include

# 사용자가 들어오는 경로를 계속 연결
urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),
                # urls.py끼리 mapping(urls를 다른 곳으로 넘겨주는 것)
    path('admin/', admin.site.urls),
]

06_Django_study/review2/review/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  {% comment %} bootstrap {% endcomment %}
  <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-reboot.min.css' %}">
  <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-grid.min.css' %}">
  <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
  {% comment %} FontAwesome {% endcomment %}
  <script src="https://kit.fontawesome.com/96e1881935.js" crossorigin="anonymous"></script>
  {% comment %} Axios {% endcomment %}
  <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
  <title>{% block title %}{% endblock title %}</title>
  
  {% comment %} base.html용도: 다른 곳에서도 불러와서 쓰자
  {% block title %}{% endblock title %}: 매번 쓰일 때 우리가 설정가능!
                                         없다면, html만들때마다 동일한 타이틀이 나옴
  {% endcomment %}
</head>
<body>
  <header>
    <h1>저희 페이지에 오신 것을 환영합니다~</h1>
    {% comment %} 사용자가 login되어있을때만 보여주는 것들 {% endcomment %}
    {% if user.is_authenticated %}
    {% comment %} user: template가 기본적으로 가지고있는 정보라 사용가능! {% endcomment %}
    <p>
      {% comment %} span : 의미를 부여하는 테그 {% endcomment %}
      <span>Hello, {{ user.username }}</span>
      <a href="{% url 'accounts:logout' %}">[로그아웃]</a>
      <a href="{% url 'accounts:update' %}">[회원정보 수정]</a>
      <form action="{% url 'accounts:delete' %}" method="post">
        {% csrf_token %}
        <button type="submit">[회원 탈퇴]</button>
      </form>
    </p>

    {% else %}
    <p>
      <a href="{% url 'accounts:login' %}">[로그인]</a>
      <a href="{% url 'accounts:signup' %}">[회원가입]</a>
    </p>


    {% endif %}
    <a href="{% url 'articles:index' %}">[목록]</a>
    {% comment %} app_name: 경로이름(urls.py의 name) {% endcomment %}
    <hr>
  </header>
  <div class="container">
  {% block container %}{% endblock container %}  
  </div>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>