06_Django_study/review2/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

# urlpatterns가 있어야 error가 안남 -> list 우선적으로 만들자!
urlpatterns = [
    # 회원가입 url 
    path('signup/', views.signup, name='signup'),
    # 로그인 url
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    # 회원탈퇴
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
        # 로그인이 되어있기때문에, user의 정보를 id값으로 판별할 필요가 없음 -> pk값 필요없음
    path('password/', views.password, name='password'),
]

06_Django_study/review2/articles/urls.py
# review에서 articles로 보내라했기 때문에 articles에서도 urls.py가 있어야 에러가 안남. 
from django.urls import path
from . import views  # 현재 app에서 view를 가지고오겠다 -> .=현재 앱

app_name = 'articles'

urlpatterns = [
    # index:현재 있는 모든 아티클들을 보여줌
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),  # 여러 앱에서 create라는 함수가 있을 수 있는데, 이름을 지정하면 이름이 나올 때 가라!
    path('<int:article_pk>/', views.detail, name='detail'),
    path('<int:article_pk>/update/', views.update, name='update'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    path('<int:article_pk>/like/', views.like, name='like'),
    path('<int:article_pk>/comment/', views.comment_create, name='comment_create'),
    path('<int:article_pk>/comment/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
    # 선생님 코드
    # path('<int:article_pk>/comments/', views.comment_create, name='comment_create'),  article_pk번째 article에 comments를 생성하겠다.
    # 삭제 시에는 article_pk가 필요없을 수도 있지만, 상속성을 나타내기 위해서
    # path('<int:article_pk>/comment/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
    path('<int:article_pk>/follow/<int:user_pk>/', views.follow, name='follow')
]

06_Django_study/review2/review/urls.py
from django.contrib import admin
from django.urls import path, include

# 사용자가 들어오는 경로를 계속 연결
urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),
                # urls.py끼리 mapping(urls를 다른 곳으로 넘겨주는 것)
    path('admin/', admin.site.urls),
]

06_Django_study/review2/articles/models.py
from django.db import models
from django.core.validators import EmailValidator, MinValueValidator
from django.conf import settings



# article.liked_users.all() -> 게시글을 좋아요 누른 사람들
# user.liked_articles.all() -> 내가 좋아요 누른 게시글들...
class Article(models.Model):  # model명은 단수로! app 이름은 보통 복수로!
    title = models.CharField(max_length=20)  # max_length: 필수적으로 들어가야함!
    content = models.TextField()  # TextField로 하는 이유: 내용이 길 수 있어서
    created_at = models.DateTimeField(auto_now_add=True)  # 날짜와 시간 동시저장
    updated_at = models.DateTimeField(auto_now=True)
    # article.user -> article을 작성한 user정보를 바로 가지고 올 수 있다.
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)  # 한명의 유저가 여러개 article생성하는데, 회원탈퇴하면 article을 삭제할 것이다 -> on_delete=models.CASCADE
    # models.py에서는 user model 쓸 때, settings로부터 직접 가지고온다 -> get_user_model()사용하지 않음
    # on_delete=models.CASCADE: 연결되어있는 관계가 끊어지면, 해당 article도 삭제
    liked_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='liked_articles')
                            # article.liked_users.all()  //  related_name -> user.liked_articles.all() 가능 
    class Meta:  # 데이터를 위한 데이터
        ordering = ('-pk', )  # tuple로 인식하도록 ,를 붙인다
        # 새로 만든 애들이 위쪽으로 쌓일 수 있도록

# 모델링 했다고 장고에게 알려주러 간다.
# $ python manage.py makemigrations -> 알려줌(실제 db에 반영시키지 않음)
        # 이때, content내용이 없어도 에러나지 않음
# $ python manage.py migrate -> 실제 db에 넣음

# 이미 만들어져있는 db에 항목 추가하려면 class에 나중에 content 추가해서 넣으려면 
# $ python manage.py makemigrations
# 1
# ''  #실제 db에 반영된 것은 아님
# $ python manage.py migrate  -> 반영


class Person(models.Model):
    name = models.CharField(max_length=10)
    email = models.CharField(
        max_length=100,
        validators=[EmailValidator(message='이메일 형식에 맞지 않습니다.')]
    )
    age = models.IntegerField(
        validators=[MinValueValidator(19, message='미성년자는 노노')]
    )


class Comment(models.Model):
    # article.comment_set.all() -> related_name 하면 article.comments.all()
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    # comment는 article에 대한 정보 가지고있음 -> comment.article 로 접근 가능
    # related_name='comments' -> article한테 뭐라고불리고싶어? 난 comments라고 불리고 싶어
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comments')  # 몇번째 article에 대한 comment인지 확인하기위해 필수! -> 1:N의 관계!!
            # on_delete 설정 : 참조한 키가 삭제되면 그 키와 관련된 데이터를 같이 삭제해주세요
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='comments')

    class Meta:  # 데이터를 위한 데이터
        ordering = ('-pk', )  # 1. tuple로 인식하도록 ,를 붙인다
                              # 2. 새로 만든 애들이 위쪽으로 쌓일 수 있도록

06_Django_study/review2/articles/forms.py
from django import forms
from .models import Article, Comment # 어느 모델의 form인지 정의할 수 있음.

# form 사용하는 가장 큰 이유: 우리가 하기 힘든것들을 알아서해주기 때문
# model form 작성하기
class ArticleForm(forms.ModelForm):

    class Meta:  # 따로 상속받을 필요없음.
        model = Article
        fields = ['title', 'content', ]  # 모든 필드를 다 가지고오겠다.

class CommentForm(forms.ModelForm):

    class Meta:  # 따로 상속받을 필요없음.
        model = Comment
        fields = ['content']  # 모든 필드를 다 가지고오겠다.
        # fields = ['content'] -> content 필드만 가지고오겠다.
        # 선생님코드 fields = '__all__' -> exclude = ['article', ]

06_Django_study/review2/articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
    # get_object_or_404: 꺼내는데, 거기에 해당하는데이터 없으면 404status코드 제공까지 알아서해줌
from .forms import ArticleForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.http import HttpResponse, JsonResponse  # 응답
from .models import Article, Comment
# from IPython import embed  # 너무 개발용.. -> 시간을 멈춘다
from django.views.decorators.http import require_POST, require_GET
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


# render: 해당 페이지를 보여준다.
# redirect: ex. delete하면 article 목록을 보여줄 때, index페이지(/article/)에서 보여줘야함으로 그리로 가달라고 버튼을 누르는 것!
@require_GET
def index(request):
    # embed()  # request에 어떤 정보가 들어있는지 확인
    # Article 모델에 있는 모든 object를 가지고 와서 html을 통해서 페이지에 보여준다.
    articles = Article.objects.all()
    context = {'articles':articles}
    return render(request, 'articles/index.html', context)


@require_GET
def detail(request, article_pk):
    # 사용자가 url에 적어보낸 article_pk를 통해 디테일 페이지를 보여준다.
    # 특정 한개의 article을 꺼내는 방법
    # 방법1.
        # model이용: Article.objects.get(pk=article_pk)  
    # 방법2.
    # article이라는 변수에 값을 가지고오는데, Article이라는 모델에서 pk에 해당하는 정보들만 가지고와라
    article = get_object_or_404(Article, pk=article_pk)
    comments = article.comments.all()
    form = CommentForm()
    context = {'article': article, 'comments': comments, 'form': form}
    return render(request, 'articles/detail.html', context)
        # return render(request, 'articles/detail.html', {'article': article})해도 위와 동일
        # 시험에 나올 수 있음!



# get: 사용자는 우리에게 작성할 수 있는 html페이지를 받아감
# post: 우리에게 받은 form(작성하는 페이지)에서 실제로 db에 작성(=아티클을 만들어라.))하겠다는 것

# post: 내가 새로 작성을 했는데, 그걸 생성하는거 = 아티클을 만들어라.
# get: 내가 내용을 작성할건데, 그 작성할수있는 form(페이지)를 보여줘라.


# 로그인이 필요하다고 말하는 것! -> 로그인이 되어있어야만 실행 가능
# 다시 돌아와 -> get요청으로만 사용 가능 ==> @requrie_POST가 안적혀있으면 작성 가능!!!
@login_required  # 위치 설정
                 # 만약 아무것도 하지않으면 기본은 '/accounts/login/'
                 # 만약 로그인관련앱 이름이 accounts가 아니면 -> (login_urls='/users/login/')과 같이 설정해야함
    # 바로 로그인 페이지로 보내줌
    # url을 accounts의 로그인으로 설정 -> django는 accounts에 기본으로 setting되어있음
    # --> /accounts/login/으로 보내줌 (이름을 설정했기때문에)
# 로그인 끝나고나면 다시 create페이지로 보내줌
# http://127.0.0.1:8000/accounts/login/?next=/articles/create/  => 로그인 후, 저 페이지로 보내라
def create(request):
    if request.method == 'POST':
        # Article을 생성해달라고 하는 요청
        # 데이터 거내서 Article 생성
        # 실제적으로 데이터를 생성.
        form = ArticleForm(request.POST)  # 사용자의 데이터를 가지고오겠다.  # title, content
        # embed()  # 잠시 코드멈춰서 shell에 들어갔다가 나오면 다시 코드 진행
                 # 데이터까지 적혀있는 것을 보여줌 
        if form.is_valid():  # 유효하지 않으면 else문가서 context에 가서 다시 rendering
            article = form.save(commit=False)  # 데이터는 저장하는 것  # 바로 db에 저장하지는 않겠다.(commit=False)
            article.user = request.user  # 지금 로그인되어있는 정보를 생성할 article의 user정보로 넣겠다.
            article.save()
            return redirect('articles:detail', article.pk)  # 여기서는 index에서 보여준느게 아니라 새로고침.
                            # 그러고나서, index에 들어가서 index가 보여주는 것!
                            # article.pk: article에서 pk를 꺼낸다
                            # article_pk: url에서에서 사용해서 넘겨지는 pk
    else:
        # GET 요청
        # Article을 생성하기 위한 페이지를 달라고 하는 요청
        # 브라우저에서 생성하고 엔터치면 나오는 페이지 보여줌
        form = ArticleForm()  # 비어있는 form
    context = {'form': form}
    return render(request, 'articles/create.html', context)  
            # templates 안에 있는 articles 폴더에 있는 create로 보내라
                # -> templates/articles/create.html에서 templates가 빠져있다고 생각!

# form: 우리가 정의한대로
# model form: form.save()하면 데이터 따로 뽑아낼 필요없이 form으로 한번에 저장

# create함수와 동일. 그러나 중복되는 부분 줄일 수 있으므로 위와같이 작성
# def create(request):
#     if request.method == 'POST':
#         form = ArticleForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect('articles:index')
#         else:
#             context = {'form': form}
#             return render(request, 'articles/create.html', context)
        
#     else: 
#         form = ArticleForm()
#         context = {'form': form}
#         return render(request, 'articles/create.html', context) 


# Article 수정/삭제, Comment 생성/삭제를 사용자 로그인 상태에서만 동작 가능하도록 만든다
# 비로그인 상태에서는 수정, 삭제할 수 없음
@login_required  # get으로만 받는 애들을 데리고올 수 있음
def update(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    # post의 목적: 기존의 아티클을 수정한 값을 바꾸줌 

    if article.user == request.user:  # 접속user와 작성user이 같으면
        if request.method == 'POST':
            # form에 request.POST로 들어온 애는 수정할 값
            form = ArticleForm(request.POST, instance=article)  # 기존에 존재하는 data에 추가
            if form.is_valid():
                form.save()
                return redirect('articles:detail', article_pk)
        else:  # GET method
            # 이때 form은 기존 처음에 작성되었던 값
            form = ArticleForm(instance=article)  # 특정 데이터를 넣은 채로 form을 보이겠다.
    else:
        return redirect('articles:detail', article_pk)
    context = {'form': form, 'article_pk': article_pk}
    return render(request, 'articles/update.html', context)
    # get : update를 이제 할 것이다 -> update페이지 여기있어
    # post: 수정하려고 데이터 들고왔구나, 원하는데로 수정해줄께. detail page로 보냄


# @login_required  : get으로 받은 애들만 사용가능!
@require_POST  # post요청 들어왔을 때만 가능!
               # get요청으로 들어오면 사용자가 이상한 방법으로 삭제하려고 한 것이다.
# articles/3/delete 를 직접 입력하면 삭제됨. -> 이를 방지해야함!!!
def delete(request, article_pk):
    if request.user.is_authenticated:
    # article_pk에 맞는 article을 꺼낸다.
    # 삭제한다. (POST, form 사용이유: 우리가 제공하는 방법으로만 삭제하게 만들기 위해!)
        article = get_object_or_404(Article, pk=article_pk)
        if article.user == request.user:
            article.delete()
        else:
            return redirect('articles:detail', article_pk)
    return redirect('articles:index')  # redirect는 get요청만 받는다.


@require_POST
def comment_create(request, article_pk):
    if request.user.is_authenticated:
        form = CommentForm(request.POST)  # 사용자가 넘겨준 데이터
        if form.is_valid():
            comment = form.save(commit=False)
            comment.article_id = article_pk
            comment.user = request.user
            comment.save()
    return redirect('articles:detail', article_pk)


# @require_POST
# def comment_create(request, article_pk):
#     # article 몇번인지 불러오기
#     article = get_object_or_404(Article, pk=article_pk)
#     if request.method == 'POST':
#         # 어떤 내용을 작성했는지, detail에서 input의 이름이 content였기때무에, request.POST.get으로 content항목을 받아온다.
#         content = request.POST.get('content')  # 사용자가 넘겨준 데이터
#         # comment라는 모델에 속하는 comment를 만들자.
#         # Comment(article=article) -> 모델에 있는 변수=지정한 aritcle이다.
#         comment = Comment(article=article)
#         # 지정한 article을 지정햇으니까 거기에 content를 넣겠다.
#         comment.content = content
#         comment.save()
#         # context = {'form': form}
        
#         return redirect('articles:detail', article_pk)



@require_POST
def comment_delete(request, article_pk, comment_pk):
    if request.user.is_authenticated:
    # article = get_object_or_404(Article, pk=article_pk) 쓸 필요가 없다!
    # why? urls에서 article_pk를 가지고와서 comment_delete(request, article_pk, comment_pk):에서 article_pk에 그대로 가지고옴
    #      detail페이지에 리턴할 때만 필요하므로 그 article_pk를 바로 redirect()안에 넣어줌!
    # 대신 article_pk = comment.article_id넣어줘도 괜찮. -> db보면 article_id있음
        comment = get_object_or_404(Comment, pk=comment_pk)
        if comment.user == request.user:
            comment.delete()
        return redirect('articles:detail', article_pk)
    else:  # else문 필요없음. 
        return HttpResponse('You are Unauthorized', status=401)
        # sessionid삭제 == 로그아웃 -> comment 삭제하기 누르면 


# # 선생님 코드 -> form 사용
# def detail(request, article_pk):
#     article = get_object_or_404(Article, pk=article_pk)
#     comment_form = CommentForm()
#     comments = Comment.objects.all()
#     context = {
#         'article': article, 
#         'comment_form': comment_form, 
#         'comments': comments
#     }
#     return render(request, 'articles/detail.html', context)


# @require_POST
# def comment_create(request, article_pk):
#     form = CommentForm(request.POST)  # 사용자가 넘겨준 데이터
#     if form.is_valid():
#         comment = form.save(commit=False)
#         comment.article_id = article_pk
#         form.save()
#     return redirect('article:detail', article_pk)


# def comment_delete(request, article_pk, comment_pk):
#     comment = get_object_or_404(Comment, pk=comment_pk)
#     comment.delete()
#     return redirect('article:detail', article_pk)


def like(request, article_pk):
    user = request.user
    article = get_object_or_404(Article, pk=article_pk)  # 필요한 정보 준비 완료

    if article.liked_users.filter(pk=user.pk).exists():  # 좋아요 목록에 있었으면 제거
    # if user in article.liked_users.all(): 윗 줄은 이 말과 동일! (효율은 윗줄이 좋음)
        # user입장에서 user가 좋아요 누른 article중에서 넘겨받은 article 추가하겠다.
        user.liked_articles.remove(article)
        liked = False
    else:  # 좋아요 목록에 없었으면 추가
        user.liked_articles.add(article)
        liked = True
    context = {'liked': liked, 'count': article.liked_users.count()}
    return JsonResponse(context)


# 사용자가 로그인 했을 때만 가능!
def follow(request, article_pk, user_pk):
    # 로그인 한 유저가 게시글 유저를 follow or unfollow 한다.
    user = request.user  # 로그인 유저
    person = get_object_or_404(get_user_model(), pk=user_pk)  # 게시글 주인

    if user in person.followers.all():  # 이미 팔로워임
        person.followers.remove(user)  # 언팔하겠음
    else:
        person.followers.add(user)  # 팔로우하겠음
    return redirect('articles:detail', article_pk)

06_Django_study/review2/articles/templates/articles/_follow.html
<div class="jumbotron text-center text-white bg-dark">
  <p class="lead mb-1">작성자 정보</p>
  <h1 class="display-4">{{ article.user.username }}</h1>
  <hr>
  <p class="lead">
    팔로잉 : {{ article.user.followings.all | length }} /
    팔로워 : {{ article.user.followers.all | length }}
  </p>

  {% if user != article.user %}
    {% if user in article.user.followers.all %}
    <a href="{% url 'articles:follow' article.pk article.user.pk  %}" class="btn btn-primary btn-lg">
    Unfollow
    </a>
    {% else %}
    <a href="{% url 'articles:follow' article.pk article.user.pk  %}" class="btn btn-primary btn-lg">
    Follow
    {% endif %}
  {% endif %}
</div>

06_Django_study/review2/articles/templates/articles/create.html
{% extends 'base.html' %}

{% block title %}Article::Create{% endblock title %}

{% comment %} Get/articles/create/ {% endcomment %}
{% comment %} POST/articles/create/ 
        -> GET과 POST 뒤에 url이 같으면 action은 ''이어도 괜찮{% endcomment %}


{% block container %}
<form method="POST" action="{% url 'articles:create' %}">
  {% csrf_token %}
{% comment %} 
  1. method: 어떻게 보낼지 지정 -> 요청보내는 방법!
  2. action: 어디로 보낼지 지정 -> 동일한 url {% endcomment %}
  {{ form.as_p }}  {% comment %} form을 사용하여 ContactForm 인스턴스를 템플릿에 전달{% endcomment %}
  
{% comment %} form을 통해  {% endcomment %}
{% comment %} 1. 어디로보낼지(url), 2. 그 url로 어떤 method사용할지 정하기  {% endcomment %}
{% comment %} 생성, 삭제, 수정 -> db에 영향을 미친다! -> method='POST' {% endcomment %}
  <button type="submit">[생성하기]</button>
</form>
{% endblock container %}

{% comment %} model form을 사용하기 위해 form 정의 
   -> 이를 통해 우리가 직접 일일이 사용자입력 확인하는 것이 아니라, 
      modelform이 유효성 검사까지 다 해줌
위쪽에서 불러오고 form생성되는지 확인 {% endcomment %}

{% comment %} 사용자들의 입력을 받아 특정한 위치(url)로 input 전달해주는 역할 {% endcomment %}

06_Django_study/review2/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block title %}Article::Detail{% endblock title %}

{% block container %}

<h2>{{ article.title }}</h2>
<p>{{ article.created_at }}</p>
<p>작성자: {{ article.user }}</p>
<hr>
{% comment %} 하트를 누르면 좋아요가 눌림 -> 하트가 버튼취급 {% endcomment %}
{% comment %} <a href="{% url 'articles:like' article.pk %}">
  {% if user in article.liked_users.all %}
    <i class="fas fa-heart fa-lg" style="color: red"></i>
  {% else %}
  <i class="far fa-heart fa-lg" style="color: red"></i>
  {% endif %}
</a> {% endcomment %}


{% comment %} 좋아요부분! 밑에 script작성!!! {% endcomment %}
{% comment %} javascript로 작성 {% endcomment %}
<i 
  class="{% if user in article.liked_users.all %}fas{% else %}far{% endif %} fa-heart fa-lg" 
  id="like-btn" 
  data-id="{{ article.pk }}"
  style="color: red"
>
</i>

{% comment %} <span>이 감싸고 있는것은 숫자, <p>는 전체를 감쌈 {% endcomment %}
<p><span id="like-count">{{ article.liked_users.all | length }}</span>명이 이 글을 좋아합니다.</p>

<p>{{ article.content }}</p>
{% comment %} a: get요청(주소창에 쓰는 것)
post: 조건달고 보내는 것(ex. 암호 -> csrf_token사용, 그래서 주소창에 쓸수없음) {% endcomment %}
{% if article.user == request.user %}
  <a href="{% url 'articles:update' article.pk %}">[수정하기]</a>
  {% comment %} 보통 POST하면 보통 form테그로 보냄 {% endcomment %}
  <form action="{% url 'articles:delete' article.pk %}" method="POST">
  {% comment %} 우리는 POST method 사용할 것이므로 method="POST" 작성해야함 {% endcomment %}
  {% csrf_token %}
  <button type="submit">[삭제하기]</button>
  </form>
{% endif %}
  {% comment %} <form action="{% url '' %}" method="POST">
  {% csrf_token %}
  <button type="submit">[삭제하기]</button>
  </form> {% endcomment %}
<hr>


<h3>Comment</h3>
{% if user.is_authenticated %}
<form action="{% url 'articles:comment_create' article.pk %}" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  {% comment %} .as_p는 p테그 형식으로 가지고오겠다. {% endcomment %}
  <button type="submit">[댓글 작성하기]</button>
</form>
{% endif %}

<ul>
{% for comment in comments %}
  <li>
    {% if comment.user == request.user %}
    <form action="{% url 'articles:comment_delete' article.pk comment.pk %}" method="POST">
    {% csrf_token %}
    <span>{{ comment.content }} = {{ comment.created_at }} / {{ comment.user }}</span>
    <button class="btn btn-danger" type="submit">[삭제하기]</button>
    </form>
    {% else %}
    <span>{{ comment.content }} = {{ comment.created_at }} / {{ comment.user }}</span>
    {% endif %}
    {% comment %} <a href="{% url 'articles:comment_delete' article.pk comment.pk %}">[댓글 삭제하기]</a></form> {% endcomment %}
  </li>
{% endfor %}
</ul>

{% include 'articles/_follow.html' %}

{% comment %} Java Script {% endcomment %}
<script>
  const likeBtn = document.querySelector('#like-btn')
  likeBtn.addEventListener('click', function(event) {
    console.log(event)
    // Button의 dataId 속성을 아래 코드로 가지고 온다
    const articleId = event.target.dataset.id
    // 이렇게는 요청까지는 보내진다. 하지만 새로고침을 해야 바뀐 브라우저를 볼 수 있음
    axios.get(`/articles/${articleId}/like/`)
      .then(function(response) {
        // console.log(response)
        // 사용자의 좋아요 상태에 따라 버튼 클래스 변경
        if(response.data.liked) { // 응답받았을 때, 사용자가 좋아요를 눌렀다면,
          // console.log(likeBtn.classList)
          likeBtn.classList.remove('far')  // event.target-> 위의 <i>(like버튼)
          likeBtn.classList.add('fas') 
        } else {
          likeBtn.classList.remove('fas')  // event.target-> 위의 <i>(like버튼)
          likeBtn.classList.add('far')
        }
        
        // Article을 좋아하는 사람들 수의 데이터를 응답받아 적용시킨다.
        const likeCount = document.querySelector('#like-count')
        likeCount.innerText = response.data.count
      })
  })
</script>
{% endblock container %}


{% comment %}

[선생님 코드]

<form action="{% url 'articles:comment_create' article.pk %}" method="POST">
  {% csrf_token %}
  {{ comment_form.as_table }}
  <button type="submit">[작성하기]</button>
</form> 
<hr>
<ul>
{% for comment in comments %}
  <li>
    <form action="{% url 'article:comment_delete' article.pk %}" method="POST">
    {% csrf_token %}
    <span>{{ comment.content }} - {{ comment.created_at }}</span>
    <button type="submit">[삭제하기]</button>
    </form>
  </li>
{% endfor %}
</ul> 
{% endcomment %}

06_Django_study/review2/articles/templates/articles/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Article::Index{% endblock title %}

{% block container %}
<h2>Article List</h2>
{% comment %} 로그인 되어있을 때만 보이도록! {% endcomment %}
{% if user.is_authenticated %}
<a href="{% url 'articles:create' %}">[생성하기]</a>
{% else %}
<p>
  <a href="{% url 'accounts:signup' %}">게시글을 작성하기 위해 지금 저희의 회원이 되어보세요!</a>
</p>
{% endif %}

{% csrf_token %}

<hr>
{% for article in articles %}
<div>
  <h3>{{ article.pk }}. {{ article.title }}</h3>
  {% comment %} articles라는 앱에서 detail이라는 이름의 url을 불러와라 article.pk:detail url에 필요하기때문에 뒤에 붙여준다. {% endcomment %}
  <p>작성자: {{ article.user }}</p>
  <a href="{% url 'articles:detail' article.pk %}">[상세보기]</a>
</div>
<br>

{% endfor %}
{% endblock container %}

06_Django_study/review2/articles/templates/articles/update.html
{% extends 'base.html' %}

{% block title %}Article::Update{% endblock title %}

{% comment %} update.html페이지가 보인다는 것은 : get요청으로 왔다는 것(주소창으로 쳐도 괜찮기때문) {% endcomment %}
{% comment %} 게시글을 수정하는 것은 주소창에서 할수없으니까 POST {% endcomment %}

{% block container %}


<form method="POST" action="{% url 'articles:update' article_pk %}">
{% comment %} <form method="POST"> 라고 써도 괜찮. why? 같은페이지로 가는 것이므로  {% endcomment %}
{% comment %} 수정하고 [수정완료]버튼을 누르면 POST한 것 -> 그러면 update함수로가서 detail페이지로 redirect함
              -> detail페이지 보여짐 {% endcomment %}
  <a href="{% url 'articles:update' article_pk %}">[수정하기]</a>  
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">[수정완료]</button>
  </form>
<hr>
{% comment %} 로그인 상태가 아니면 아예 수정하기 버튼을 누를 수 없다. {% endcomment %}


{% endblock container %}